import nn_part_one from "./img/nn_part_one.jpg"

export const itemData = [
	{id: 1, img: nn_part_one, title: "Neural Networks: Part 1", href: "./posts/nn_part_one"},
];

export const galleryImages = [
	{img: "https://lh6.googleusercontent.com/F_otV2IU668zBMmuryqiwe5Mu5YuwOOqdvw2eyKcqWiRhOpEpDtY6zsDBPCXzWodx1U=w2400", date: "", desc: "Hello"},
	{img: "https://lh6.googleusercontent.com/Dp5n4nGfrvlYR6wndXgow19FeeThFheRKuRLlcwj2UQ9H8tB3XpWwrD-2HXlSmUOv_E=w2400", date: "", desc: "Cup"},
	{img: "https://lh3.googleusercontent.com/dRa4zWPFb6X1tKtCvmlD5UfY0qPBXIY-Y_HgLpKpYYoES-icQ1JZK2Hq1cpo0GRnJ3I=w2400", date: "", desc: "These charming winter streets reminded me of my first New Year's Eve in this city"},
	{img: "https://lh5.googleusercontent.com/RzTXOJknThiyz7i7H1bHfxO7RaC3QjtcSquQHJSQwGjkYCZo9cnI7eRt5ZjrRWBtYcI=w2400", date: "", desc: "The day my friend decided to build a raft at the junkyard and carry it to the river to swim across it"},
	{img: "https://lh5.googleusercontent.com/pA-Qxzk5KQqhJpqaSSf5HWPkisjm18X4qc4RzYt92Cinme8YkoFguFBrK31QdvTDN2Y=w2400", date: "", desc: "We walked through this wasteland listening to the main theme of 'The Good the Bad and the Ugly'"},
	{img: "https://lh5.googleusercontent.com/HJoeb0kECAP5pCXYOUOs1zlKJn9TbtRRwi6XB-6TgKgxL5XcXAp8yK9a8o6sINB28_E=w2400", date: "", desc: "The last warm days here before I moved to Siberia. We found the records that day as we were walking the streets that looked like Greece and listening to music from Zorba the Greek."},
	{img: "https://lh4.googleusercontent.com/u9IrRbd6w9no38pvC6Ur2HS-XJYPpBIfMTCsFyv-I313_z06HYPxYpUU0ZxkqDpXEiI=w2400", date: "", desc: "Gorno-Altaysk"},
	{img: "https://lh4.googleusercontent.com/uDG1o6nZchUB2Ce1AkR4hW-Zn6PsV7d7bQik1JD-1Wp_UMW3l1LvpHgv8QrRmt9yddg=w2400", date: "", desc: "Rainy morning"},
	{img: "https://lh6.googleusercontent.com/XvqoNeHxcGZVP8AxngyTHRum5UFU2FL6UuoXbcRUnrOPgSNMnw0LpI0DInAysufM070=w2400", date: "", desc: "Me"},
	{img: "https://lh5.googleusercontent.com/8FfoG3LnxoRemCwxRvRYtFE9TZdQPQuacuT6pZ7BYttJgRBqnzZkllUE-DZxBO13Owo=w2400", date: "", desc: "Misty road"},
	{img: "https://lh5.googleusercontent.com/K6mzrp6--cx3DKPlMRV0S9Z2jfmMtsiYmceawISoVBZKL6CP-miWnjmB5OEQzD5H2pM=w2400", date: "", desc: "Valley"},
	{img: "https://lh4.googleusercontent.com/gaF1fcGvj9-gawumm_CMfaEnXxvh2KhvctLlIgHoaqs_NDBIT6KH8neX5uAkKQbbtYY=w2400", date: "", desc: "Houses"},
	{img: "https://lh5.googleusercontent.com/Og4Dk9d6ez7ygzloxsRp7REProoXsByrS93U1RcGpK1xwDyqpcKFNnrev5WA7TXSn5w=w2400", date: "", desc: "Children of freedom"},
	{img: "https://lh5.googleusercontent.com/V1zGuJfWHenyW48Rcq1tW2tbDBgTAv-ugJM-7v-Nka0LCqGdpzD0pav3t0hLHEgtlrM=w2400", date: "", desc: "Everything in this world exists because it exists and happens because it happens. There're no mysteries, everything is ridiculously obvious."},
	{img: "https://lh6.googleusercontent.com/zMvALU_JpQC0aHL8UOMrhv_8b2UTID3oGStQiPyYVf_Fud_PWQKtTuGvJkA5qi9WPQU=w2400", date: "", desc: "Cow"},
	{img: "https://lh6.googleusercontent.com/b53GvmRR2JAICTDv0kY6P4njD9cEwWHx-XjLt6nXrQeq7S00_SvV3s8pNqampKECiiA=w2400", date: "", desc: "Balance"},
	{img: "https://lh5.googleusercontent.com/yw2LVJzl1aRvyiTCUpVWvDKIS0RIOGswY50ihRzJZHHr40x2fU_ZPkZVbHxDq4hgxnQ=w2400", date: "", desc: "Village"},
	{img: "https://lh4.googleusercontent.com/EsC9IN2e5kSu1HoLi_9Nj9P_QaU1SrXAYVrW1aReZeC01SOHxqvNJvlcSB7YONUcuKA=w2400", date: "", desc: "Dream"},
	{img: "https://lh3.googleusercontent.com/C21Ln9NAYbYsHgQAswcYH9VfUV4NFhhMNkKWMSy2CFDZS_g1E_PTk1MZtFjXsm-69HM=w2400", date: "", desc: "Rest"},
	{img: "https://lh6.googleusercontent.com/cfB46PnpslEGuRlPrNJ76cXnI0a56D9jHY6sYWdmAoKZLMZsxaOArKwoo8FqMP4OJn4=w2400", date: "", desc: "Corey"},
	{img: "https://lh3.googleusercontent.com/pJdikpIxeiPt8UOAB57t1gbdtk8XOLlb3p_XE_agV7kUYxLXfIMDOAFbqKmONxG9pmI=w2400", date: "", desc: "Mayhem"},
	{img: "https://lh4.googleusercontent.com/kHLENnY65QioY1i6kP3lk7LVxUR_e8W0lNKYYNH1hLEdawt85_6QXdpY2FXjWQy4IXk=w2400", date: "", desc: "Hardwork"},
	{img: "https://lh5.googleusercontent.com/3mu3LjEH3jZ02ah5M7HzJ3VSoGFKLUrcAqxuyP7ke-59QDNYglf0DH397Y1bHmss1VU=w2400", date: "", desc: "Mouse"},
	{img: "https://lh3.googleusercontent.com/9ceiNj0xH-fDw3RM4JYo6cpVj77OaLzjvu-EdREsDVJfIAwUCSBf6ogDbH-yje5Z6dM=w2400", date: "", desc: "Cornfield"},
	{img: "https://lh6.googleusercontent.com/ITpg6Wr9hpftHKo2J8JglfV7Wjs21Llw8voTy_cPgCVM8vAx-bcIY_WdyHCsoNr4rVo=w2400", date: "", desc: "Solitude"},
	{img: "https://lh5.googleusercontent.com/8AKDd0BZddZostB7ATL1QvLOt9meS-cknlJlAGM02MVxICLRNS-8tQIvMa2KVMJPNSg=w2400", date: "", desc: "Cat"},
	{img: "https://lh5.googleusercontent.com/I__NpOm1Gat3DBs9Ss9OAPWSPTxSFWeZZjeTvA_T82oAB1-rRTNR8gL3Lxi389sz13k=w2400", date: "", desc: "Spot"},
	{img: "https://lh3.googleusercontent.com/D0LcJHva2P5YXblt9ny3eMwenjCzmKbA80TVtBPBx7rxppRnyU8W-EsDWvQ7WjukrSI=w2400", date: "", desc: "Reidh"},
	{img: "https://lh4.googleusercontent.com/iqK36Na6fsI9GyfAO88ktJokLkeIP5Qj4wtcLWcKwdb1aYX6MhG6Q_a4cH88vBTSv00=w2400", date: "", desc: "Heart"},
	{img: "https://lh3.googleusercontent.com/M8fty90CBQDEnAdQftJgc5wNps9ocXCqwWRtnA6uvIhja4fX5NDbnKb-pvSHsDRTtXQ=w2400", date: "", desc: "Horizonts"},
	{img: "https://lh4.googleusercontent.com/sfZYVussSvNrXyJznOEGVDDsS4eR9ipvJxrgV8G_0h732-dATx9ulBbMSFUjdBBOllE=w2400", date: "", desc: "Zaton"},
	{img: "https://lh6.googleusercontent.com/t_lBtB8POp7is3L6eCecn3V77MzBOCOHTcIfdYcPdRvJv3yZ9CODXxf71H01DzDHLlU=w2400", date: "", desc: "Night"},
	{img: "https://lh4.googleusercontent.com/SEGdiutNtl0eLrXqBmXyi-S1A6tRVqnhoJb78ndwZhURQZuyr-iCbsd-wAg94ShjiIA=w2400", date: "", desc: "Churchill"},
	{img: "https://lh4.googleusercontent.com/zPmx_d5pk5yneZZ5O9lC9pMMIHSfTWsH8KJZuwXrzi92juGwDFnaEpAzMQk0xVtLyp4=w2400", date: "", desc: "Guest"},
	{img: "https://lh4.googleusercontent.com/YeFUDB62wG6PTg8XSvEzZjWgFOXtojAn3jdi1MEwkORdE_7vXWaxL0iOppy5Ho6EfTc=w2400", date: "", desc: "Buddha"},
	{img: "https://lh6.googleusercontent.com/kmWcswvHKFdxbCLK7yGCs8KOb2LtliE50dRllX99Up54H8NJ8VYO8QSNUycRQd2L0CU=w2400", date: "", desc: "Varg"},
	{img: "https://lh4.googleusercontent.com/6M8E1prJ6j8M6tvaTcUcO6r5Ll2r2J-GIAx5Ik8L1eVcCPZ7wWS7lwfgiudXdozuIM4=w2400", date: "", desc: "Dad"},
	{img: "https://lh4.googleusercontent.com/5bDvKKls8PeW5EMZpBAlPv1J35yZSi6b9Ld5B_sIy2DeP88J-jpk4IAreh2FbHKQVYs=w2400", date: "", desc: "Lena Forest"},
	{img: "https://lh4.googleusercontent.com/H-khGGnmCnK3fK9jaxtOqSmoaT8JN3wkk8zQFdoat2wJaxnEvBHJuZiocP3OWbhQM0Q=w2400", date: "", desc: "Forest"},
	{img: "https://lh5.googleusercontent.com/opzpx53abjEovQCVjqdzyOrB1BiuIxiw5hqT34-6DYtXtcchjhz5LehLE9bYU9O3z8Y=w2400", date: "", desc: "Rock"},
	{img: "https://lh4.googleusercontent.com/2BnTeorHG1xm5J8ZX5iEebIWYmi5S1AIRIWaUCTV6Ok4kMSMttpOXXJhJE1jhJrmzD0=w2400", date: "", desc: "Bears"},
	{img: "https://lh4.googleusercontent.com/oZBWPMPjJlZC9I2QshPPx99HxRcCer0Kgjtb7xDqKwwqTHNkh4PP0XBYbCgHx26nrIc=w2400", date: "", desc: "Rainbow"},
	{img: "https://lh3.googleusercontent.com/LlV-DdHBuQv5UWHxYkG3cEAMBocpZUgTnfVcSERouXvLgDzcn4yHPAM-SU_looe3LXs=w2400", date: "", desc: "Mushrooms"},
	{img: "https://lh6.googleusercontent.com/LD0zH1sX5XvDNHmkMEQpdtwFc_ZNJQtWC0qCgwDMWKl6fykdHVG7AJgEwPQyLupKjNY=w2400", date: "", desc: "Our place"},
	{img: "https://lh4.googleusercontent.com/hi8Rd0DuhytKp92MVZmYd6PKvS1D-mgKACGBf-WbT2DmFMRg0n4HL3DB4dVJ7ZDH6Q8=w2400", date: "", desc: "Parrot"},
	{img: "https://lh6.googleusercontent.com/QD5Ue-cs2Bqai3hXgBGzg4A2kgx69YyEZ15xUSD_3UFcTXPTSrWw_earesQTqs1owDc=w2400", date: "", desc: "Cat"},
	{img: "https://lh6.googleusercontent.com/retJwwOSoaaeuQGOPPnHCldTI0d9f7LAoz1Yl17cjBUKRgtFpeBa_qPU-lrLNCR9vVA=w2400", date: "", desc: "Butterfly"},
	{img: "https://lh6.googleusercontent.com/q4rNvzN2Ny3jTsmf7AeyOEQ2hDzUV6NQK8-flsxMPIWEbbLRmp11_i6loXIPIG3Ayhg=w2400", date: "", desc: "Photo"},
	{img: "https://lh4.googleusercontent.com/o14eHKb0mrcFgrrpdllsTGwBUyzrrC7N9w3t-_c-OnfATlYmcy2xdlo9lK1JinX_mvI=w2400", date: "", desc: "Mandarin"},
	{img: "https://lh5.googleusercontent.com/4VIfO0Lr9jCeNVXEnYq0aCzikwRH9plCxD10UIVt2vXZQ_3h0aaiSv4DwVorqaD8y9g=w2400", date: "", desc: "Orenburg"},
	{img: "https://lh3.googleusercontent.com/IxKxTqOQ1jgWAy0JTQouklUBwXH0zCXbZjXV07e1BPpMNSmQTXia1Ddb6g1rqZRkrgY=w2400", date: "", desc: "Tugrik"},
	{img: "https://lh3.googleusercontent.com/B9nJUXnDaeL426dEeAYbJVVx4CHew5ElU0BakptLOVCp3flqQJv6LI2xCcESBVxkDL0=w2400", date: "", desc: "Contemplation"},
	{img: "https://lh5.googleusercontent.com/tIs0SL-Tf-61qLtGALUH3UU065cSZxD0q7Fv1OUHYLM8oqvTVZ0m9pkIM6RhNNUXMNI=w2400", date: "", desc: "Pizza"},
	{img: "https://lh3.googleusercontent.com/pERbzXK_tk3o4nPzDheUrR6YElwFWrcbWve5Day7kGJCMOXfA27eFIvUGvq3LJ-KBl8=w2400", date: "", desc: "Business"},
	{img: "https://lh5.googleusercontent.com/F9blWdVsvEYftFytJJlmZarPuuOt44aFJybp1En1mwAZH0WSELjhEP4W2sXVaT4XNnk=w2400", date: "", desc: "Angel"},
	{img: "https://lh3.googleusercontent.com/sta0zMPBm-YrnMCIsO1QEMh3-qysBZOb7ZQVZK1fPhXMyXwIgFOPSNSQIs3-bQ_b9Yk=w2400", date: "", desc: "Novosibirsk"},
	{img: "https://lh3.googleusercontent.com/eWE9JT-Fa7o1KBGcIB2ktHElrLyWrTYZ1fEYLD5CBESaM5EZ6-7St0SNZ3fFdN50yrQ=w2400", date: "", desc: "Cool"},
	{img: "https://lh4.googleusercontent.com/vaeS8TCfXCZdcrrMkgQdh4_k03zU_ihF6jJD5tvCSRcf-mz-cPU3SDzPw7Plcxxy8Qg=w2400", date: "", desc: "Babylon"},
	{img: "https://lh6.googleusercontent.com/zbim0s1fMVjq4etOJqHXiDDW2DkoqM9ygPObCsZnRF-eU9J0DMZ7T8RtlT5BJL4LwkU=w2400", date: "", desc: "Skeleton"},
	{img: "https://lh3.googleusercontent.com/vmQtxFdCOF3nW8DJFR9Y2dK7FN5majIjcVw7djNqXtvd73mfoArkH8PoXRtZTtybxDo=w2400", date: "", desc: "Tree"},
	{img: "https://lh5.googleusercontent.com/BD9jBwXZKkXevqCtsn5DjF-aPenS3roC4POshGw3sS6v9yZeQvLUI6KY7n_WM9mqReA=w2400", date: "", desc: "Cat"},
	{img: "https://lh3.googleusercontent.com/XUBzrNrRyV3qNdwJVg5eYVmh7W97atq4jJD_8QAaNAtmrbveefWbBFolAtwGMYbDPuE=w2400", date: "", desc: "Key"},
	{img: "https://lh6.googleusercontent.com/3n8ToaJDQsT-zWglCS4Tz3xw2U3ot34_YKlIUkTq5UeX2oW1T18Jw58aXZI6rHv3Wb0=w2400", date: "", desc: "Hand"},
	{img: "https://lh6.googleusercontent.com/f4Uy4C6oV4ktNeXGPaBkoixJxxLnaYN_qgiofbpkmggoVjT-Yd7Vi7sm4HBn2Ec3ghA=w2400", date: "", desc: "Moment"},
	{img: "https://lh6.googleusercontent.com/5bBaDhtvMKitaajpdSBn-T2ZQMZYdtfvrZt2iVlwStkmv4lUtU7izbp_MSH6ettbUt0=w2400", date: "", desc: "Party"},
	{img: "https://lh3.googleusercontent.com/5PpISo4HSeN26Ekh0iSizMsF4zGbLKcerW-Ifi4PhABr0QSHvXPj1evrgh0e9NI__sc=w2400", date: "", desc: "Zina"},
	{img: "https://lh5.googleusercontent.com/fDMDuYrwvy4xx2zjR6C5PT4LvgdFto5FCHqShzgZEottDIo1RBMC5q5nD9E2UtaH_h8=w2400", date: "", desc: "Me eating"},
	{img: "https://lh5.googleusercontent.com/nbmyD_HWPtuVdqUGwAbry0ixB7BF02UfaQBaDIhS6M3ugZxHg6lxarFH4rA6tg3V34c=w2400", date: "", desc: "Zaeltsovskaya"},
	{img: "https://lh4.googleusercontent.com/2gKIm0HuSQI8kyUsdxc7H5fC4o5xaKpOXyFcv__wpxmlZ96s136Q5IxxJY2V7eyVzWo=w2400", date: "", desc: "Haipovaya fotka"},
	{img: "https://lh6.googleusercontent.com/lfiV_DM2Aq54IulBdApO8php4ILaeSzsf6E5YpQiPPHzDTMAHJfamk7tGeraCN7lCvg=w2400", date: "", desc: "Studies"},
	{img: "https://lh3.googleusercontent.com/PwsS7T22HzOX6_qOIk7zLkN1GFMxYJ5rWh_cMQqYvleFIkEwo0u3Gpbj8hTQjXTnjQM=w2400", date: "", desc: "King size"},
	{img: "https://lh3.googleusercontent.com/PYH9o2sv4X29oIBcZ91SSQ7eV1iArWC9bMooXhJKNe4iexXJ5WzB9Av1ox5bFW9XFcU=w2400", date: "", desc: "Willpower"},
	{img: "https://lh3.googleusercontent.com/ssd-U2TP9Y4GSJUYzO2YfQhN4sOcD6akXLO21ZcC8bQ77PbVUXante3PB_m-7ydFwKc=w2400", date: "", desc: "Contemplation"},
	{img: "https://lh5.googleusercontent.com/NTeYcpkV3LctCFH8yNzsATf50iJp-gEhBTjJLgsuIXJ2cUhpI7QEP3foVhy9t00oUMM=w2400", date: "", desc: "Behemoth"},
	{img: "https://lh3.googleusercontent.com/i8RHHtzq3Kd1Sf2mRgB2_2ug8PzbY4st8P3ovehuLYWEixf_Fx4obcnjwH0pFdjZYlc=w2400", date: "", desc: "Barnaul"},
	{img: "https://lh5.googleusercontent.com/uGms2SobwBuVCaKhjDiPrAhgm5iya0nTA9HGyJPedELodKR68sqZh1CA1yKp3RNMKqo=w2400", date: "", desc: "Theater"},
	{img: "https://lh5.googleusercontent.com/x9HSipfPQ44F6RARSYKB2zkNb7beygUFzFuDi6PKe0JK8l_tvCBjEhJBqzn6B_yuDSI=w2400", date: "", desc: "Workday"},
	{img: "https://lh4.googleusercontent.com/r3CqEfQqFWNQhsqGKqgU0p5Ma5FptGQcs0iveGi7EsVFwPQmGBvA_sNe0mLemSkO4UU=w2400", date: "", desc: "Euphory"},
	{img: "https://lh3.googleusercontent.com/S87SVAIb2D6wO484eicYzoNNzRDy-8W9COydy-39Fpdgb-Z8YL40x0md7pPgOFPm7Mw=w2400", date: "", desc: "Lust"},
	{img: "https://lh3.googleusercontent.com/g8RdeQB-BUUBKdQrx_7uphcHwzFfmHTBkmKLn479avQJxtPHj--zItZ7Fr9knSxsylg=w2400", date: "", desc: "Jam"},
	{img: "https://lh5.googleusercontent.com/vwjcCepviBQD8i-L5ReWrmBHz785pFOEapiOrBwLuvKdk2M0xstaKu_CzzIOU2660uI=w2400", date: "", desc: "Varg"},
	{img: "https://lh5.googleusercontent.com/15Gp82Iykb8vt9-Oatl7uWs2dc0uWHix3Q_lZFkTHdhro7F3zh8wTKnN57DT6gf_-bc=w2400", date: "", desc: "Long way"},
	{img: "https://lh4.googleusercontent.com/q40l1rZf8c48szfD3xgTfGTWcs4C7oMURVDaI15mVYsBGVfmEHQcfavBfA6EQQ8JJTw=w2400", date: "", desc: "School years"},
	{img: "https://lh4.googleusercontent.com/bs-0oSG7uRQa6KLKbk3eoWhvmR_Vf39WQ2iwUIw1b458alanFfwRKPdgdVrQOzIAM5Q=w2400", date: "", desc: "Truckers"},
];

export const achievementsArr = [
    {status: 'c', text: 'Plank for 10 min.', type: '💪', date: '08.05.2021'},
    {status: 'u', text: 'Безумно отметить окончание вуза', type: '👁️', date: ''},
    {status: 'u', text: 'Жим лёжа 100 кг.', type: '💪', date: ''},
    {status: 'u', text: 'Reading for 100 days in a row', type: '', date: ''},
    {status: 'u', text: '100 дней тренировок подряд', type: '', date: ''},
    {status: 'u', text: 'Жим лёжа 100 кг.', type: '', date: ''},
    {status: 'u', text: '200 отжиманий за подход', type: '', date: ''},
    {status: 'u', text: '20 выходов силой за подход', type: '', date: ''},
    {status: 'u', text: '10 минут виса на турнике', type: '', date: ''},
    {status: 'u', text: 'Питаться правильно 6 месяцев подряд', type: '', date: ''},
    {status: 'u', text: 'Делать утреннюю зарядку 6 месяцев подряд', type: '', date: ''},
    {status: 'u', text: '100 дней пробежек подряд', type: '', date: ''},
    {status: 'u', text: 'Planche', type: '', date: ''},
    {status: 'u', text: 'Human flag', type: '', date: ''},
    {status: 'u', text: 'Пробежать марафон', type: '', date: ''},
    {status: 'u', text: '60 минут планки', type: '', date: ''},
    {status: 'u', text: '20 вертикальных отжиманий без опоры', type: '', date: ''},
    {status: 'u', text: 'Начать зарабатывать n долларов в месяц', type: '', date: ''},
    {status: 'u', text: 'Начать зарабатывать n долларов в месяц пассивно', type: '', date: ''},
    {status: 'u', text: 'Организовать путешествие для родителей', type: '', date: ''},
    {status: 'u', text: 'Неделю быть в полном одиночестве на природе без интернета', type: '', date: ''},
    {status: 'u', text: 'Начать работать полностью удалённо с гибким графиком', type: '', date: ''},
    {status: 'u', text: '1000 дней медитации', type: '', date: ''},
    {status: 'u', text: 'Диплом бакалавра', type: '', date: ''},
    {status: 'u', text: 'Проплыть 5 км.', type: '', date: ''},
    {status: 'u', text: 'Become a Scuba Diver and explore underwater caves', type: '', date: ''},
    {status: 'u', text: 'Сапборд', type: '', date: ''},
    {status: 'c', text: 'Начать жить отдельно от родителей до 18 лет', type: '', date: ''},
    {status: 'u', text: '30 дней общения только на иностранном языке', type: '', date: ''},
    {status: 'u', text: 'Получить второе гражданство', type: '', date: ''},
    {status: 'u', text: 'Живое выступление на иностранном языке', type: '', date: ''},
    {status: 'u', text: 'Выучить всю карту мира: расположение стран и столиц', type: '', date: ''},
    {status: 'u', text: 'Посетить 1000 мест трэвел-карты', type: '', date: ''},
    {status: 'u', text: 'Прожить 3 года в путешествии', type: '', date: ''},
    {status: 'u', text: 'Написать 10 научных статей по машинному обучению', type: '', date: ''},
    {status: 'u', text: 'Товарные поезда с Кондором и балалайкой', type: '', date: ''},
    {status: 'u', text: 'Прожить 12 месяцев, откладывая 90% зарплаты', type: '', date: ''},
    {status: 'u', text: 'Начать получать $100 в день с депозитов', type: '', date: ''},
    {status: 'u', text: '24 месяца цифрового самоконтроля (пояснить)', type: '', date: ''},
    {status: 'u', text: 'Просыпаться рано 12 месяцев подряд (пояснить)', type: '', date: ''},
    {status: 'u', text: 'Совершить кругосветное путешествие (ссылка на заметку)', type: '', date: ''},
    {status: 'u', text: 'Поплавать во всех океанах', type: '', date: ''},
    {status: 'u', text: 'Путешествие в доме на колёсах', type: '', date: ''},
    {status: 'u', text: 'Мотопутешествие по Америкам', type: '', date: ''},
    {status: 'u', text: 'Мотопутешествие по Евразии', type: '', date: ''},
    {status: 'u', text: '200к км. путешествий по суши', type: '', date: ''},
    {status: 'u', text: 'К 25 годам побывать в 50 странах', type: '', date: ''},
    {status: 'u', text: 'Побывать во всех государствах-членах ООН', type: '', date: ''},
    {status: 'u', text: '100 дней путешествовать без трат на жильё', type: '', date: ''},
    {status: 'u', text: 'Achieve a $1,000,000 net worth', type: '', date: ''},
    {status: 'u', text: 'Ночь наблюдения за звездами', type: '', date: ''},
    {status: 'u', text: 'Speak conversational Spanish', type: '', date: ''},
    {status: 'u', text: 'Speak English fluently', type: '', date: ''},
    {status: 'u', text: 'Выпить виски с Данилой под Whiskey Man', type: '', date: ''},
    {status: 'u', text: 'Заработать $10к на криптовалютном рынке', type: '', date: ''},
    {status: 'u', text: 'Заработать $10к на фондовом рынке', type: '', date: ''},
    {status: 'u', text: 'Get six-pack abs', type: '', date: ''},
    {status: 'u', text: 'Переплыть Средиземное море на паруснике', type: '', date: ''},
    {status: 'u', text: 'Читать каждый день как минимум по часу в день 100 дней подряд', type: '', date: ''},
    {status: 'u', text: 'Контрастный душ 100 дней подряд', type: '', date: ''},
    {status: 'u', text: 'Занять должность Senior', type: '', date: ''},
    {status: 'u', text: 'Kaggle grandmaster', type: '', date: ''},
    {status: 'u', text: 'Стать фрилансером', type: '', date: ''},
    {status: 'u', text: 'Подружиться с 5 случайными прохожими', type: '', date: ''},
    {status: 'u', text: 'Попробовать мухомор', type: '', date: ''},
    {status: 'u', text: 'Bungee jump', type: '', date: ''},
    {status: 'u', text: 'Kayaking', type: '', date: ''},
    {status: 'u', text: 'Прокатиться на сноуборде', type: '', date: ''},
    {status: 'u', text: 'Побывать в космосе', type: '', date: ''},
    {status: 'u', text: 'Выпить ром на Кубе с Кондором под кубинскую музыку и музыку из Tropico', type: '', date: ''},
    {status: 'u', text: 'Погружение в батискафе', type: '', date: ''},
    {status: 'u', text: 'Skydiving, incl. wingsuit flying', type: '', date: ''},
    {status: 'u', text: 'Zipline', type: '', date: ''},
    {status: 'u', text: 'Rafting', type: '', date: ''},
    {status: 'u', text: 'Downhill', type: '', date: ''},
    {status: 'u', text: 'Полетать на вертолёте', type: '', date: ''},
    {status: 'u', text: 'Переехать в англоязычную страну', type: '', date: ''},
    {status: 'u', text: 'Become a good father', type: '', date: ''},
    {status: 'u', text: 'Степень магистра', type: '', date: ''},
    {status: 'u', text: 'Побывать на трёх концертах любимых групп', type: '', date: ''},
    {status: 'u', text: 'Пострелять из лука и разного огнестрельного оружия на полигоне', type: '', date: ''},
];

 

















